name = "idiotquant-nextjs"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[[d1_databases]]
binding = "db" # 코드에서 env.db로 쓸 이름
database_name = "idiotquant"
database_id = "00274a9d-6771-4a90-9af6-6b03cacd722a"